services:
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats-data:/data # Mount volume
    command:
      - "-js" # Enable JetStream
      - "-sd" # Store directory
      - "/data" # Path lưu data
      - "-m" # Monitoring
      - "8222"
volumes:
  nats-data:
