{{- if .Values.payment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: {{ .Values.payment.replicas }}
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: {{ .Values.payment.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.payment.port.grpc }}
            - containerPort: {{ .Values.payment.port.http }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: journey-secrets
                  key: PAYMENT_DATABASE_URL
            - name: PORT
              value: {{ .Values.payment.port.http | quote }}
            - name: PAYMENT_GRPC_SERVICE_URL
              value: "0.0.0.0:{{ .Values.payment.port.grpc }}"
          envFrom:
            - configMapRef:
                name: journey-config
            - secretRef:
                name: journey-secrets
{{- end }}