{{- if .Values.auth.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: {{ .Values.auth.replicas }}
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: {{ .Values.auth.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.auth.port.grpc }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: journey-secrets
                  key: AUTH_DATABASE_URL
            - name: AUTH_GRPC_SERVICE_URL
              value: "0.0.0.0:{{ .Values.auth.port.grpc }}"
          envFrom:
            - configMapRef:
                name: journey-config
            - secretRef:
                name: journey-secrets
{{- end }}