{{- if .Values.admin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: admin
  labels:
    app: admin
spec:
  type: LoadBalancer
  selector:
    app: admin
  ports:
    - protocol: TCP
      port: {{ .Values.admin.port.http }}
      targetPort: {{ .Values.admin.port.http }}
      name: http
{{- end }}
