{{- if .Values.user.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: {{ .Values.user.replicas }}
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: {{ .Values.user.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.user.port.grpc }}
            - containerPort: {{ .Values.user.port.http }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: journey-secrets
                  key: USER_DATABASE_URL
            - name: PORT
              value: {{ .Values.user.port.http | quote }}
            - name: USER_GRPC_SERVICE_URL
              value: "0.0.0.0:{{ .Values.user.port.grpc }}"
          envFrom:
            - configMapRef:
                name: journey-config
{{- end }}