{{- if .Values.rental.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: rental
  labels:
    app: rental
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: {{ .Values.rental.port.grpc }}
      targetPort: grpc
      protocol: TCP
  selector:
    app: rental
{{- end }}
