{{- if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: {{ .Values.api.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.api.port.http }}
          env:
            - name: PORT
              value: {{ .Values.api.port.http | quote }}
          envFrom:
            - configMapRef:
                name: journey-config
            - secretRef:
                name: journey-secrets
{{- end }}