{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - protocol: TCP
      port: {{ .Values.api.port.http }}
      targetPort: {{ .Values.api.port.http }}
      name: http
{{- end }}
