// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.1
// source: chat.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "chat";

/** Chat */
export interface Chat {
  id: string;
  fromUserId: string;
  toUserId: string;
  content: string;
  createdAt: string;
}

/** GetChats */
export interface GetChatsRequest {
  fromUserId: string;
  toUserId: string;
  page: number;
  limit: number;
}

export interface GetChatsResponse {
  chats: Chat[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

/** CreateChat */
export interface CreateChatRequest {
  fromUserId: string;
  toUserId: string;
  content: string;
}

export interface CreateChatResponse {
  id: string;
  fromUserId: string;
  toUserId: string;
  content: string;
  createdAt: string;
}

/** GetManyConversations */
export interface GetManyConversationsRequest {
  adminId: string;
  page: number;
  limit: number;
}

export interface GetManyConversationsResponse {
  conversations: string[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

/** Complaint */
export interface Complaint {
  id: string;
  userId: string;
  title: string;
  status: string;
  createdAt: string;
  updatedAt: string;
}

/** GetManyComplaints */
export interface GetManyComplaintsRequest {
  status?: string | undefined;
  page: number;
  limit: number;
}

export interface GetManyComplaintsResponse {
  complaints: Complaint[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

/** CreateComplaint */
export interface CreateComplaintRequest {
  userId: string;
  title: string;
}

export interface GetComplaintResponse {
  id: string;
  userId: string;
  title: string;
  status: string;
  createdAt: string;
  updatedAt: string;
}

/** UpdateComplaintStatus */
export interface UpdateComplaintStatusRequest {
  id: string;
  status: string;
}

/** ComplaintMessage */
export interface ComplaintMessage {
  id: string;
  complaintId: string;
  senderId: string;
  messageType: string;
  content: string;
  createdAt: string;
}

/** GetManyComplaintMessages */
export interface GetManyComplaintMessagesRequest {
  complaintId: string;
  page: number;
  limit: number;
}

export interface GetManyComplaintMessagesResponse {
  complaintMessages: ComplaintMessage[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

/** CreateComplaintMessage */
export interface CreateComplaintMessageRequest {
  complaintId: string;
  senderId: string;
  messageType: string;
  content: string;
}

export const CHAT_PACKAGE_NAME = "chat";

export interface ChatServiceClient {
  getChats(request: GetChatsRequest): Observable<GetChatsResponse>;

  createChat(request: CreateChatRequest): Observable<CreateChatResponse>;

  getManyConversations(request: GetManyConversationsRequest): Observable<GetManyConversationsResponse>;

  getManyComplaints(request: GetManyComplaintsRequest): Observable<GetManyComplaintsResponse>;

  createComplaint(request: CreateComplaintRequest): Observable<GetComplaintResponse>;

  updateComplaintStatus(request: UpdateComplaintStatusRequest): Observable<GetComplaintResponse>;

  getManyComplaintMessages(request: GetManyComplaintMessagesRequest): Observable<GetManyComplaintMessagesResponse>;

  createComplaintMessage(request: CreateComplaintMessageRequest): Observable<ComplaintMessage>;
}

export interface ChatServiceController {
  getChats(request: GetChatsRequest): Promise<GetChatsResponse> | Observable<GetChatsResponse> | GetChatsResponse;

  createChat(
    request: CreateChatRequest,
  ): Promise<CreateChatResponse> | Observable<CreateChatResponse> | CreateChatResponse;

  getManyConversations(
    request: GetManyConversationsRequest,
  ): Promise<GetManyConversationsResponse> | Observable<GetManyConversationsResponse> | GetManyConversationsResponse;

  getManyComplaints(
    request: GetManyComplaintsRequest,
  ): Promise<GetManyComplaintsResponse> | Observable<GetManyComplaintsResponse> | GetManyComplaintsResponse;

  createComplaint(
    request: CreateComplaintRequest,
  ): Promise<GetComplaintResponse> | Observable<GetComplaintResponse> | GetComplaintResponse;

  updateComplaintStatus(
    request: UpdateComplaintStatusRequest,
  ): Promise<GetComplaintResponse> | Observable<GetComplaintResponse> | GetComplaintResponse;

  getManyComplaintMessages(
    request: GetManyComplaintMessagesRequest,
  ):
    | Promise<GetManyComplaintMessagesResponse>
    | Observable<GetManyComplaintMessagesResponse>
    | GetManyComplaintMessagesResponse;

  createComplaintMessage(
    request: CreateComplaintMessageRequest,
  ): Promise<ComplaintMessage> | Observable<ComplaintMessage> | ComplaintMessage;
}

export function ChatServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getChats",
      "createChat",
      "getManyConversations",
      "getManyComplaints",
      "createComplaint",
      "updateComplaintStatus",
      "getManyComplaintMessages",
      "createComplaintMessage",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ChatService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ChatService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CHAT_SERVICE_NAME = "ChatService";
