// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: payment.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "payment";

export interface WebhookPaymentRequest {
  id: number;
  gateway: string;
  transactionDate: string;
  accountNumber?: string | undefined;
  code?: string | undefined;
  content?: string | undefined;
  transferType: string;
  transferAmount: number;
  accumulated: number;
  subAccount?: string | undefined;
  referenceCode?: string | undefined;
  description: string;
}

export interface GetPaymentRequest {
  id: string;
  userId: string;
}

export interface GetPaymentAdminRequest {
  id: string;
}

export interface GetPaymentResponse {
  id: string;
  sequenceNumber: number;
  paymentCode: string;
  userId: string;
  type: string;
  bookingId?: string | undefined;
  rentalId?: string | undefined;
  amount: number;
  status: string;
  createdAt: string;
  updatedAt?: string | undefined;
}

export interface GetManyPaymentsRequest {
  userId?: string | undefined;
  type?: string | undefined;
  status?: string | undefined;
  paymentCode?: string | undefined;
  page: number;
  limit: number;
}

export interface GetManyPaymentsResponse {
  payments: GetPaymentResponse[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

export interface WebhookPaymentResponse {
  message: string;
}

export interface GetRefundRequest {
  id: string;
  userId: string;
}

export interface GetRefundAdminRequest {
  id: string;
}

export interface GetRefundResponse {
  id: string;
  userId: string;
  bookingId?: string | undefined;
  rentalId?: string | undefined;
  principal: number;
  amount: number;
  penaltyAmount: number;
  damageAmount: number;
  overtimeAmount: number;
  status: string;
  createdAt: string;
  updatedAt: string;
}

export interface GetManyRefundsRequest {
  userId?: string | undefined;
  status?: string | undefined;
  page: number;
  limit: number;
}

export interface GetManyRefundsResponse {
  refunds: GetRefundResponse[];
  page: number;
  limit: number;
  totalItems: number;
  totalPages: number;
}

/** UpdateRefundStatus */
export interface UpdateRefundStatusRequest {
  id: string;
  status: string;
}

export const PAYMENT_PACKAGE_NAME = "payment";

export interface PaymentServiceClient {
  receiver(request: WebhookPaymentRequest): Observable<WebhookPaymentResponse>;

  getPayment(request: GetPaymentRequest): Observable<GetPaymentResponse>;

  getPaymentAdmin(request: GetPaymentAdminRequest): Observable<GetPaymentResponse>;

  getManyPayments(request: GetManyPaymentsRequest): Observable<GetManyPaymentsResponse>;

  getRefund(request: GetRefundRequest): Observable<GetRefundResponse>;

  getManyRefunds(request: GetManyRefundsRequest): Observable<GetManyRefundsResponse>;

  updateRefundStatus(request: UpdateRefundStatusRequest): Observable<GetRefundResponse>;

  getRefundAdmin(request: GetRefundAdminRequest): Observable<GetRefundResponse>;
}

export interface PaymentServiceController {
  receiver(
    request: WebhookPaymentRequest,
  ): Promise<WebhookPaymentResponse> | Observable<WebhookPaymentResponse> | WebhookPaymentResponse;

  getPayment(
    request: GetPaymentRequest,
  ): Promise<GetPaymentResponse> | Observable<GetPaymentResponse> | GetPaymentResponse;

  getPaymentAdmin(
    request: GetPaymentAdminRequest,
  ): Promise<GetPaymentResponse> | Observable<GetPaymentResponse> | GetPaymentResponse;

  getManyPayments(
    request: GetManyPaymentsRequest,
  ): Promise<GetManyPaymentsResponse> | Observable<GetManyPaymentsResponse> | GetManyPaymentsResponse;

  getRefund(request: GetRefundRequest): Promise<GetRefundResponse> | Observable<GetRefundResponse> | GetRefundResponse;

  getManyRefunds(
    request: GetManyRefundsRequest,
  ): Promise<GetManyRefundsResponse> | Observable<GetManyRefundsResponse> | GetManyRefundsResponse;

  updateRefundStatus(
    request: UpdateRefundStatusRequest,
  ): Promise<GetRefundResponse> | Observable<GetRefundResponse> | GetRefundResponse;

  getRefundAdmin(
    request: GetRefundAdminRequest,
  ): Promise<GetRefundResponse> | Observable<GetRefundResponse> | GetRefundResponse;
}

export function PaymentServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "receiver",
      "getPayment",
      "getPaymentAdmin",
      "getManyPayments",
      "getRefund",
      "getManyRefunds",
      "updateRefundStatus",
      "getRefundAdmin",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("PaymentService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("PaymentService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PAYMENT_SERVICE_NAME = "PaymentService";
