name: CI/CD

on:
  push:
    branches: [service]
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - name: api
            dockerfile: apps/api/Dockerfile
          - name: auth
            dockerfile: apps/auth/Dockerfile
          - name: notification
            dockerfile: apps/notification/Dockerfile
          - name: user
            dockerfile: apps/user/Dockerfile

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Setup protoc
        uses: arduino/setup-protoc@v3.0.0

      - name: Configure Git protocol
        run: git config --global url."https://github.com/".insteadOf git://github.com/

      - run: npm ci --legacy-peer-deps

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Tạo unique tag từ commit SHA
      - name: Generate tag
        id: tag
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.service.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/journey-${{ matrix.service.name }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/journey-${{ matrix.service.name }}:${{ steps.tag.outputs.TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    if: github.event_name != 'pull_request'

    steps:
      - uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save ${{ secrets.DIGITALOCEAN_CLUSTER_ID }}

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: "latest"

      - name: Generate tag
        id: tag
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      # Decode secrets file
      - name: Create secrets file
        run: |
          echo "${{ secrets.HELM_SECRETS_PRODUCTION }}" | base64 -d > secrets.production.yaml

      - name: Upgrade Helm Release
        run: |
          helm upgrade journey ./charts/journey \
            -f secrets.production.yaml \
            --namespace journey \
            --set api.enabled=true \
            --set auth.enabled=true \
            --set user.enabled=true \
            --set notification.enabled=true \
            --set api.image=${{ secrets.DOCKERHUB_USERNAME }}/journey-api:${{ steps.tag.outputs.TAG }} \
            --set auth.image=${{ secrets.DOCKERHUB_USERNAME }}/journey-auth:${{ steps.tag.outputs.TAG }} \
            --set notification.image=${{ secrets.DOCKERHUB_USERNAME }}/journey-notification:${{ steps.tag.outputs.TAG }} \
            --set user.image=${{ secrets.DOCKERHUB_USERNAME }}/journey-user:${{ steps.tag.outputs.TAG }} \
            --wait \
            --timeout 5m

      - name: Verify Deployment
        run: |
          kubectl get pods -n journey
          kubectl rollout status deployment/api -n journey --timeout=3m
          kubectl rollout status deployment/auth -n journey --timeout=3m
          kubectl rollout status deployment/notification -n journey --timeout=3m
          kubectl rollout status deployment/user -n journey --timeout=3m
