name: CI

on:
  push:
    branches: [service]
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - name: api
            dockerfile: apps/api/Dockerfile
          - name: auth
            dockerfile: apps/auth/Dockerfile
          - name: notification
            dockerfile: apps/notification/Dockerfile
          - name: user
            dockerfile: apps/user/Dockerfile

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Setup protoc
        uses: arduino/setup-protoc@v3.0.0

      - run: npm ci --legacy-peer-deps

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.service.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/journey-${{ matrix.service.name }}:latest
